# Generated by Django 5.0.1 on 2024-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='longtitude',
            field=models.FloatField(default=1),
        ),
    ]
