# Generated by Django 5.0.2 on 2024-02-28 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.location'),
        ),
    ]
