# Generated by Django 5.0.1 on 2024-03-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_location_latitude_alter_location_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default='Default description', max_length=100),
        ),
    ]
