# Generated by Django 5.0.1 on 2024-03-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_location_alter_tasktype_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='C:/Users/yushi/OneDrive/Desktop/group/ecm2434/mysite/db/Profile_Picture/profile.jpg', upload_to='profile_pictures/'),
        ),
    ]
