# Generated by Django 5.0.1 on 2024-03-12 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_location_alter_tasktype_location"),
        ("leaderboard", "0002_alter_leaderboardentry_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertask",
            name="userName",
        ),
        migrations.RenameField(
            model_name="usertask",
            old_name="taskID",
            new_name="task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="taskID",
        ),
        migrations.RemoveField(
            model_name="task",
            name="taskType",
        ),
        migrations.RemoveField(
            model_name="task",
            name="time",
        ),
        migrations.RemoveField(
            model_name="usertask",
            name="time",
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default="Default description"),
        ),
        migrations.AddField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="latitude",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="longitude",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="Untitled Task", max_length=255),
        ),
        migrations.AddField(
            model_name="usertask",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertask",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertask",
            name="description",
            field=models.TextField(default="Default description"),
        ),
        migrations.AddField(
            model_name="usertask",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
