# Generated by Django 5.0.1 on 2024-03-20 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.location'),
        ),
    ]
