# Generated by Django 5.0.1 on 2024-03-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_usertask_username_rename_taskid_usertask_task_and_more'),
        ('db', '0003_uploadedimage_user_profile_picture'),
    ]

    operations = [
    ]
