# Generated by Django 5.0.1 on 2024-03-18 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_merge_20240318_2101'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='Default description')),
                ('image', models.ImageField(upload_to='images/')),
                ('latitude', models.FloatField(default=1)),
                ('longtitude', models.FloatField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='longitude',
            new_name='longtitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='typeID',
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.location'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.tasktype'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='description',
            field=models.CharField(default='Default description', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='taskName',
            field=models.CharField(default='recycle', max_length=100),
        ),
        migrations.AddField(
            model_name='completetask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.task'),
        ),
        migrations.AddField(
            model_name='completetask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
