# Generated by Django 5.0.1 on 2024-03-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_completetask_delete_uploadedimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetask',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
